classNames:
  '0':
    name: 'Falling'
    color: [176,58,46]
  '1':
    name: 'Standing'
    color: [46, 204, 113]
  '2':
    name: 'Sitting'
    color: [241, 196, 15]
alert:
  name: 'Alert'
  text: 'Sending a alert !!!'
  color: [255, 0, 0]
model:
  path: 'path'
  confidence: 50
  confidence_visibility: False
  compression: 70
  image_test: 'path'
  verbose: False
  classes_detect: [0,1,2]
  time_alert: 5
  classes_detect: [0,1,2]
api:
  address: '0.0.0.0'
  port: 8000
frontend:
  path: 'path'
slack:
  token: ''
  channelid: ''
