services:
  backend-api:
    image: DOCKER_IMAGE
    volumes:
      - ./config-docker.yaml:/config/config-docker.yaml
    environment:
      - PORT=8000
      - CONFIG_FILE=/config/config-docker.yaml
    ports:
      - 8000:8000
