apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: NAME_APP
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containers:
      - image: DOCKER_IMAGE
        resources:
            limits:
              cpu: 2000m
              memory: 2Gi
        env:
        - name: CONFIG_FILE
          value: /config/config-docker.yaml
        volumeMounts:
        - mountPath: /config
          name: configuration
      volumes:
      - name: configuration
        secret:
          items:
          - key: KEY
            path: config-docker.yaml
          secretName: SECRET_NAME
